### PR TITLE
Display application icon in the "Open With" menu

### PR DESCRIPTION
**Pull request by puux**
A small but nice addition:

![preview]
(http://i.mcgl.ru/yz23I2J5iG)

### CODE REVIEW

**Comment by turboscholz** [comment]
I tried your patch but strangely I do not get any icon in the popupmenu. I have his behavior also without your patch, maybe because of some settings in my environment. Do you have an idea why this happens? Do you use Gnome? I use Xfce.
bildschirmfoto_2016-07-14_18-49-24

**Comment by puux** [comment]
I also use Xfce. And I also encountered this problem and spent a long time with her :)

Gnome Commander for creating file pop-up menu using gnome-app-helper api. This api to display icons checks the flag /desktop/gnome/interface/menus_have_icons. To set this flag to true, use the command:
gconftool --type boolean --set "/desktop/gnome/interface/menus_have_icons" "true"
or use gconf editor.

I think it would be nice to rewrite this part using direct api to create a menu, so that other users had no such problems. What do you think?

**Comment by turboscholz** [comment]
Great, now it works for me, too. Very nice.

Yes, we should definitely do this - most of the libraries used by gcmd are very old and outdated. But first let me finish switching from [gconfig to GSettings](https://bugzilla.gnome.org/show_bug.cgi?id=570733) as this changes a lot of code on different places.

When this is done, we should oben up a new git development branch. For the moment, I think the best idea would be to put a hint about the icons on the project homepage.

PS: By the end of next week I'll be off for some days because of vacation. So don't be confused when I don't respond to your messages for some time. :)

**Comment by puux** [comment]
Have a nice holiday :) I 'll do until the bugs .

**Pull request closed without merging**
