### PR TITLE
Sync bookmarks between all instances of gnome-commander

### PR DESCRIPTION
**Pull request by puux**
How it work:

![preview]
(http://i.mcgl.ru/oMgobQhyOr)

This feature covers of similar from TODO "Write bookmark changes immediately to file".

Together with bookmarks synchronized all that is stored in the XML file.

Plese test this feature :)

### CODE REVIEW

**Comment by turboscholz** [comment]
Works nice, but I found a small bug: When you delete a bookmark in the bookmark dialog and now click on another existing bookmark in this dialog, gcmd crashes. The debugger is pointing to line 307 in [dialogs/gnome-cmd-manage-bookmarks-dialog.cc](https://github.com/puux/gnome-commander/blob/36c9eef1d2cad9b142255baf8e11060269cf415d/src/dialogs/gnome-cmd-manage-bookmarks-dialog.cc#L307) and this doesn't happen without the patch.

I currently couldn't identify the root cause for this problem. Do you have an idea?

**Comment by puux** [comment]
I was able to repeat this bug with only two copies of the application, when one opened bookmark editing dialog, but from a different tab is removed. This occurs because the tabs are recreated after the change, and in the dialogue are old links.

**Comment by puux** [comment]
He added a patch that updates the bookmark in the bookmarks manager. Сheck on its version please.

**Comment by turboscholz** [comment]
Thank you! I tested your patch, it works nicely. Merged.

**Pull request closed without merging**
